---

- name: Setup MySQL for testing
  hosts: db
  tasks:
    - name: Install mysql
      ansible.builtin.yum:
        name: "@mysql"
        state: present
    - name: Start and enable MySQL
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
    - name: Set root password
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ db_root_passwd }}"
        encrypted: false
    - name: Create testing db
      community.mysql.mysql_db:
        name: testing
        state: present
    - name: Create testing user
      community.mysql.mysql_user:
        name: test
        password: "{{ db_test_passwd }}"
        encrypted: false
        state: present
        priv:
          'testing.*': 'ALL'


