---

- name: Setup MySQL for testing
  hosts: all
  tasks:
    - name: Install mysql
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - "@mysql"
        - python3-PyMySQL
    - name: Start and enable MySQL
      ansible.builtin.service:
        name: mysqld
        state: started
        enabled: yes
    - name: Set root password
      community.mysql.mysql_user:
        name: root
        host: localhost
        password: "{{ db_root_passwd }}"
        encrypted: false
        login_password: "{{ db_root_passwd }}"
    - name: Create testing db
      community.mysql.mysql_db:
        name: testing
        state: present
        login_password: "{{ db_root_passwd }}"
    - name: Create testing user
      community.mysql.mysql_user:
        name: test
        password: "{{ db_test_passwd }}"
        encrypted: false
        state: present
        login_password: "{{ db_root_passwd }}"
        priv:
          'testing.*': 'ALL'


