---
- name: Test
  hosts: 127.0.0.1
  connection: local
  vars:
    db_host: 10.242.64.5
    db_port: 3306
  tasks:
    - name: Set MySQL date query
      set_fact:
        minute_query: "{{ ansible_date_time.date }} {{ ansible_date_time.hour }}:{{ ansible_date_time.minute }}:*"
        #minute_query: "{{ ansible_date_time.date }}%"

    - name: Get hosts
      community.mysql.mysql_query:
        login_host: "{{ db_host }}"
        login_db: testing
        login_user: root
        login_password: "{{ mysql_passwd }}"
        login_port: "{{ db_port }}"
        query: 'select * from patching where scheduled_update_time like "{{ minute_query }}"'
      register: mysql_results

    - name: Add hosts to Inv
      ansible.builtin.add_host:
        name: "{{ item.server }}"
        groups: patching
        id: "{{ item.id }}"
      loop: "{{ mysql_results.query_result[0] }}"

- name: Run something
  hosts: patching
  connection: local
  vars:
    db_host: 10.242.64.5
    db_port: 3306
  tasks:
    - name: Dummy update block
      block:
        - name: Get to_fail
          shell: "echo $(($RANDOM%2))"
          register: to_fail_result
        - name: Set to_fail fact
          set_fact:
            to_fail: "{{ to_fail_result.stdout }}"
        - name: Debug to_fail result
          debug:
            var: to_fail
        - name: Set wait time in minutes (1-15)
          shell: shuf -i 1-5 -n 1
          register: wait_time

        - name: Pause for simulated update
          ansible.builtin.pause:
            minutes: "{{ wait_time.stdout }}"
        - name: "true"
          shell: "/bin/true"
          when: to_fail == "0"
        - name: "false"
          shell: "/bin/false"
          when: to_fail == "1"

        - name: Update MySQL DB
          community.mysql.mysql_query:
            login_host: "{{ db_host }}"
            login_db: testing
            login_user: root
            login_password: "{{ mysql_passwd }}"
            login_port: "{{ db_port }}"
            query: "update patching set status = 'Updated' where id=%s"
            positional_args:
              - "{{ id }}"
      rescue:
        - name: Update failed - update MySQL
          community.mysql.mysql_query:
            login_host: "{{ db_host }}"
            login_db: testing
            login_user: root
            login_password: "{{ mysql_passwd }}"
            login_port: "{{ db_port }}"
            query: "update patching set status = 'Failed' where id=%s"
            positional_args:
              - "{{ id }}"
